apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-mtool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-mtool
    template:
      metadata:
        labels:
          app: busybox-mtool
      spec:
        containers:
        - name: busybox
          image: busybox
          command: ["/bin/sh", "-c", "while :; do sleep 5; do date >> /share/date.txt; done"]
          volumeMounts:
          - name: share
            mountPath: /share
        - name: multitool
          image:  wbitt/network-multitool
          volumeMounts:
          - name: share
            mountPath: /share
        volumeMounts:
        - name: share
          emptyDir: {}
